I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 139, in script call
    call expression ft from _call_expression
  File "game/showdown.rpy", line 888, in script
    if (isk<1000 and dg == 1):
  File "game/showdown.rpy", line 899, in <module>
    elif (isk>=1000 and dg == 0):
NameError: name 'dg' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 139, in script call
    call expression ft from _call_expression
  File "game/showdown.rpy", line 888, in script
    if (isk<1000 and dg == 1):
  File "C:\Program Files\renpy-7.3.2-sdk\renpy\ast.py", line 1830, in execute
    if renpy.python.py_eval(condition):
  File "C:\Program Files\renpy-7.3.2-sdk\renpy\python.py", line 2035, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Program Files\renpy-7.3.2-sdk\renpy\python.py", line 2028, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/showdown.rpy", line 899, in <module>
    elif (isk>=1000 and dg == 0):
NameError: name 'dg' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.2.320
An Ideal Student in 30 Days! 1.0
Mon Oct 21 13:49:07 2019
